### ISSUE TITLE
mysql的有吗?还是直接用其他架构的也行?

### ISSUE THREAD

**Issue by windsome** [wojiushixiaobai/docker-library-loong64#1]
mysql的有吗?还是直接用其他架构的也行?

**Comment by wojiushixiaobai** [comment]
@windsome 
老哥，MySQL 的龙芯自己提供了。你直接用就行，我这边是直接用了自己编译的 MariaDB。
https://cr.loongnix.cn/repository/library/mysql?tab=tags 

相关链接：
- https://github.com/Loongson-Cloud-Community/mysql-debian
- https://github.com/Loongson-Cloud-Community/dockerfiles/blob/main/library/mysql/5.7.39/Dockerfile

很抱歉，我今天才看到这个消息，希望回复对你有帮助。
